In [2]:
import polars as pl
from paths import ROOT_DIR, DATA_DIR

In [11]:
train_df = pl.read_ndjson(ROOT_DIR / "data/LibriSpeech-sint/manifest.jsonl")

In [12]:
train_df.columns

['audio_filepath',
 'text',
 'language',
 'condition',
 'duration',
 'sample_rate',
 'utterance_id']

In [13]:
train_df["duration"].describe()

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 114156.0  │
│ null_count ┆ 0.0       │
│ mean       ┆ 12.688853 │
│ std        ┆ 3.574606  │
│ min        ┆ 1.41      │
│ 25%        ┆ 11.62     │
│ 50%        ┆ 13.995    │
│ 75%        ┆ 15.165    │
│ max        ┆ 24.525    │
└────────────┴───────────┘

In [14]:
train_df["duration"].sum() / 60 / 60

402.3635166666665

In [15]:
import random


def create_stratified_dataset(
    df: pl.DataFrame, target_hours: float = 100.0
) -> pl.DataFrame:
    target_seconds = target_hours * 3600

    rows = df.iter_rows(named=True)
    rows = list(rows)
    random.shuffle(rows)

    selected = []
    total_seconds = 0.0
    for row in rows:
        if total_seconds >= target_seconds:
            break
        selected.append(row)
        total_seconds += row["duration"]

    result_df = pl.DataFrame(selected).select(
        [
            "audio_filepath",
            "text",
            "language",
            "condition",
            "duration",
            "sample_rate",
            "utterance_id",
        ]
    )

    print(f"Total duration: {total_seconds / 3600:.2f}h")
    print(f"Total rows: {len(result_df)}")
    print(
        f"Condition distribution:\n{result_df['condition'].value_counts().sort('condition')}"
    )

    return result_df


result = create_stratified_dataset(train_df, target_hours=100.0)

Total duration: 100.00h
Total rows: 28345
Condition distribution:
shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 7160  │
│ good      ┆ 7056  │
│ okay      ┆ 7061  │
│ perfect   ┆ 7068  │
└───────────┴───────┘

In [16]:
from pathlib import Path


def copy_and_write_manifest(
    df: pl.DataFrame,
    input_dir: str,
    output_dir: str,
    manifest_path: str,
) -> pl.DataFrame:
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    audio_dir = output_dir / "audio"

    new_rows = []

    for row in tqdm(df.iter_rows(named=True), total=len(df), desc="Copying audio"):
        src = input_dir / row["audio_filepath"]

        condition_dir = audio_dir / row["condition"]
        condition_dir.mkdir(parents=True, exist_ok=True)

        dst = condition_dir / f"{row['utterance_id']}{src.suffix}"
        shutil.copy2(src, dst)

        row["audio_filepath"] = str(
            dst.relative_to(output_dir)
        )  # relative to output_dir
        new_rows.append(row)

    new_df = pl.DataFrame(new_rows).select(
        [
            "audio_filepath",
            "text",
            "language",
            "condition",
            "duration",
            "sample_rate",
            "utterance_id",
        ]
    )

    new_df.write_ndjson(manifest_path)
    print(f"Manifest written to: {manifest_path}")
    print(f"Audio files copied to: {audio_dir}")
    print(f"Total files: {len(new_df)}")
    print(f"Total duration: {new_df['duration'].sum() / 3600:.2f}h")

    return new_df


new_df = copy_and_write_manifest(
    df=result,
    input_dir=DATA_DIR / "LibriSpeech-sint",
    output_dir=DATA_DIR / "LibriSpeech-train-sim-100h",
    manifest_path=DATA_DIR / "LibriSpeech-train-sim-100h/manifest.jsonl",
)

Copying audio: 100%|██████████| 28345/28345 [00:19<00:00, 1457.82it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-train-sim-100h/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-train-sim-100h/audio
Total files: 28345
Total duration: 100.00h

In [17]:
small_subset = create_stratified_dataset(train_df, target_hours=40)

new_df = copy_and_write_manifest(
    df=small_subset,
    input_dir=DATA_DIR / "LibriSpeech-sint",
    output_dir=DATA_DIR / "LibriSpeech-train-sim-40h",
    manifest_path=DATA_DIR / "LibriSpeech-train-sim-40h/manifest.jsonl",
)

Total duration: 40.00h
Total rows: 11317
Condition distribution:
shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 2780  │
│ good      ┆ 2805  │
│ okay      ┆ 2879  │
│ perfect   ┆ 2853  │
└───────────┴───────┘

Copying audio: 100%|██████████| 11317/11317 [00:05<00:00, 2101.78it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-train-sim-40h/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-train-sim-40h/audio
Total files: 11317
Total duration: 40.00h

In [18]:
random_path = Path("/home/ezka/vhf-bak/data/ESC50-sint/manifest.jsonl")

In [19]:
random_df = pl.read_ndjson(random_path)

In [20]:
random_df = create_stratified_dataset(random_df, target_hours=0.2)

Total duration: 0.20h
Total rows: 144
Condition distribution:
shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 31    │
│ good      ┆ 42    │
│ okay      ┆ 30    │
│ perfect   ┆ 41    │
└───────────┴───────┘

In [23]:
copy_and_write_manifest(
    df=random_df,
    input_dir="/home/ezka/vhf-bak/data/ESC50-sint",
    output_dir="/home/ezka/vhf-bak/data/ESC50-sint-20m",
    manifest_path="/home/ezka/vhf-bak/data/ESC50-sint-20m/manifest.jsonl",
)

Copying audio: 100%|██████████| 144/144 [00:00<00:00, 1252.31it/s]

Manifest written to: /home/ezka/vhf-bak/data/ESC50-sint-20m/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/ESC50-sint-20m/audio
Total files: 144
Total duration: 0.20h

shape: (144, 7)
┌───────────────────────────┬──────┬──────────┬───────────┬──────────┬─────────────┬───────────────┐
│ audio_filepath            ┆ text ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id  │
│ ---                       ┆ ---  ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---           │
│ str                       ┆ str  ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str           │
╞═══════════════════════════╪══════╪══════════╪═══════════╪══════════╪═════════════╪═══════════════╡
│ audio/bad/2-103426-A-3.wa ┆      ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 2-103426-A-3  │
│ v                         ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/okay/2-68595-A-15.w ┆      ┆ en       ┆ okay      ┆ 5.0      ┆ 16000       ┆ 2-68595-A-15  │
│ av                        ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/perfect/1-208757-B- ┆      ┆ en       ┆ perfect   ┆ 5.0      ┆ 16000       ┆ 1-208757-B-2  │
│ 2.wav                     ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/perfect/2-60794-A-2 ┆      ┆ en       ┆ perfect   ┆ 5.0      ┆ 16000       ┆ 2-60794-A-26  │
│ 6.wav                     ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/bad/1-40621-A-28.wa ┆      ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 1-40621-A-28  │
│ v                         ┆      ┆          ┆           ┆          ┆             ┆               │
│ …                         ┆ …    ┆ …        ┆ …         ┆ …        ┆ …           ┆ …             │
│ audio/bad/2-122763-A-29.w ┆      ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 2-122763-A-29 │
│ av                        ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/good/4-181708-A-32. ┆      ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 4-181708-A-32 │
│ wav                       ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/bad/5-127990-A-2.wa ┆      ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 5-127990-A-2  │
│ v                         ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/perfect/1-101336-A- ┆      ┆ en       ┆ perfect   ┆ 5.0      ┆ 16000       ┆ 1-101336-A-30 │
│ 30.wa…                    ┆      ┆          ┆           ┆          ┆             ┆               │
│ audio/good/3-164594-A-15. ┆      ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 3-164594-A-15 │
│ wav                       ┆      ┆          ┆           ┆          ┆             ┆               │
└───────────────────────────┴──────┴──────────┴───────────┴──────────┴─────────────┴───────────────┘

In [1]:
from pathlib import Path
import polars as pl


def merge_datasets(
    dataset_dirs: list[str | Path],
    output_dir: str | Path,
) -> pl.DataFrame:
    output_dir = Path(output_dir)
    audio_dir = output_dir / "audio"
    manifest_path = output_dir / "manifest.jsonl"

    all_rows = []

    for dataset_dir in dataset_dirs:
        dataset_dir = Path(dataset_dir)
        manifest = dataset_dir / "manifest.jsonl"

        df = pl.read_ndjson(manifest)

        for row in tqdm(
            df.iter_rows(named=True), total=len(df), desc=f"Copying {dataset_dir.name}"
        ):
            src = dataset_dir / row["audio_filepath"]

            condition_dir = audio_dir / row["condition"]
            condition_dir.mkdir(parents=True, exist_ok=True)

            dst = condition_dir / f"{row['utterance_id']}{src.suffix}"

            # Handle collisions: if same utterance_id exists from another dataset
            if dst.exists():
                dst = (
                    condition_dir
                    / f"{dataset_dir.name}__{row['utterance_id']}{src.suffix}"
                )

            shutil.copy2(src, dst)

            row["audio_filepath"] = str(dst.relative_to(output_dir))
            all_rows.append(row)

    new_df = pl.DataFrame(all_rows).select(
        [
            "audio_filepath",
            "text",
            "language",
            "condition",
            "duration",
            "sample_rate",
            "utterance_id",
        ]
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    new_df.write_ndjson(manifest_path)

    print(f"Manifest written to: {manifest_path}")
    print(f"Audio files copied to: {audio_dir}")
    print(f"Total files: {len(new_df)}")
    print(f"Total duration: {new_df['duration'].sum() / 3600:.2f}h")
    print(f"Conditions: {new_df['condition'].value_counts().sort('condition')}")

    return new_df

In [25]:
merge_datasets(
    dataset_dirs=[DATA_DIR / "LibriSpeech-train-sim-100h", DATA_DIR / "ESC50-sint-20m"],
    output_dir=DATA_DIR / "LibriSpeech-train-final",
)

Copying LibriSpeech-train-sim-100h: 100%|██████████| 28345/28345 [00:05<00:00, 5318.76it/s]
Copying ESC50-sint-20m: 100%|██████████| 144/144 [00:00<00:00, 7831.28it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-train-final/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-train-final/audio
Total files: 28489
Total duration: 100.20h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 7191  │
│ good      ┆ 7098  │
│ okay      ┆ 7091  │
│ perfect   ┆ 7109  │
└───────────┴───────┘

shape: (28_489, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/perfect/ ┆ THE INFANT     ┆ en       ┆ perfect   ┆ 15.895   ┆ 16000       ┆ 8425-291444-00 │
│ 8425-291444-00 ┆ YEARS OF OUR   ┆          ┆           ┆          ┆             ┆ 13             │
│ 13…            ┆ CITY T…        ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ CHAPTER TWENTY ┆ en       ┆ perfect   ┆ 15.105   ┆ 16000       ┆ 3807-4955-0000 │
│ 3807-4955-0000 ┆ FIVE THE       ┆          ┆           ┆          ┆             ┆                │
│ .w…            ┆ FLIGHT…        ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/481 ┆ THERE WERE     ┆ en       ┆ okay      ┆ 15.61    ┆ 16000       ┆ 481-123719-000 │
│ -123719-0006.w ┆ MOMENTS OF     ┆          ┆           ┆          ┆             ┆ 6              │
│ av             ┆ SUCH POS…      ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/89- ┆ TO CLOSE HER   ┆ en       ┆ okay      ┆ 15.29    ┆ 16000       ┆ 89-218-0054    │
│ 218-0054.wav   ┆ EYES IN SLEEP  ┆          ┆           ┆          ┆             ┆                │
│                ┆ THA…           ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ BUT STOOD      ┆ en       ┆ perfect   ┆ 15.695   ┆ 16000       ┆ 3526-176653-00 │
│ 3526-176653-00 ┆ STILL WINDING  ┆          ┆           ┆          ┆             ┆ 08             │
│ 08…            ┆ SOMETH…        ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/bad/2-12 ┆                ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 2-122763-A-29  │
│ 2763-A-29.wav  ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/4-1 ┆                ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 4-181708-A-32  │
│ 81708-A-32.wav ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/5-12 ┆                ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 5-127990-A-2   │
│ 7990-A-2.wav   ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆                ┆ en       ┆ perfect   ┆ 5.0      ┆ 16000       ┆ 1-101336-A-30  │
│ 1-101336-A-30. ┆                ┆          ┆           ┆          ┆             ┆                │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/3-1 ┆                ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 3-164594-A-15  │
│ 64594-A-15.wav ┆                ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [26]:
merge_datasets(
    dataset_dirs=[DATA_DIR / "LibriSpeech-train-sim-40h", DATA_DIR / "ESC50-sint-20m"],
    output_dir=DATA_DIR / "LibriSpeech-train-small",
)

Copying LibriSpeech-train-sim-40h: 100%|██████████| 11317/11317 [00:02<00:00, 5082.81it/s]
Copying ESC50-sint-20m: 100%|██████████| 144/144 [00:00<00:00, 7501.08it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-train-small/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-train-small/audio
Total files: 11461
Total duration: 40.20h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 2811  │
│ good      ┆ 2847  │
│ okay      ┆ 2909  │
│ perfect   ┆ 2894  │
└───────────┴───────┘

shape: (11_461, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/bad/1963 ┆ SEASONABLE     ┆ en       ┆ bad       ┆ 14.86    ┆ 16000       ┆ 1963-142776-00 │
│ -142776-0011.w ┆ FROM JUNE TO   ┆          ┆           ┆          ┆             ┆ 11             │
│ av             ┆ MARCH …        ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/311 ┆ WHENCE IT      ┆ en       ┆ okay      ┆ 14.175   ┆ 16000       ┆ 311-124404-008 │
│ -124404-0083.w ┆ HAPPENS THAT   ┆          ┆           ┆          ┆             ┆ 3              │
│ av             ┆ IF THE …       ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ FOR TO IT      ┆ en       ┆ perfect   ┆ 13.7     ┆ 16000       ┆ 4397-15668-003 │
│ 4397-15668-003 ┆ HUNDREDS OF    ┆          ┆           ┆          ┆             ┆ 4              │
│ 4.…            ┆ THEM OWE…      ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ TAKE IT TAKE   ┆ en       ┆ perfect   ┆ 13.61    ┆ 16000       ┆ 5322-7680-0023 │
│ 5322-7680-0023 ┆ IT IF YOU      ┆          ┆           ┆          ┆             ┆                │
│ .w…            ┆ DON'T Y…       ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/489 ┆ THE RIVER      ┆ en       ┆ okay      ┆ 16.14    ┆ 16000       ┆ 4898-28461-001 │
│ 8-28461-0017.w ┆ REJOICING IN   ┆          ┆           ┆          ┆             ┆ 7              │
│ av             ┆ ITS STR…       ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/bad/2-12 ┆                ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 2-122763-A-29  │
│ 2763-A-29.wav  ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/4-1 ┆                ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 4-181708-A-32  │
│ 81708-A-32.wav ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/5-12 ┆                ┆ en       ┆ bad       ┆ 5.0      ┆ 16000       ┆ 5-127990-A-2   │
│ 7990-A-2.wav   ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆                ┆ en       ┆ perfect   ┆ 5.0      ┆ 16000       ┆ 1-101336-A-30  │
│ 1-101336-A-30. ┆                ┆          ┆           ┆          ┆             ┆                │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/3-1 ┆                ┆ en       ┆ good      ┆ 5.0      ┆ 16000       ┆ 3-164594-A-15  │
│ 64594-A-15.wav ┆                ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [9]:
merge_datasets(
    dataset_dirs=[
        DATA_DIR / "LibriSpeech-dev-clean-sint",
        DATA_DIR / "LibriSpeech-dev-other-sint",
    ],
    output_dir=DATA_DIR / "LibriSpeech-dev-combined",
)

Copying LibriSpeech-dev-clean-sint: 100%|██████████| 10812/10812 [00:05<00:00, 2029.13it/s]
Copying LibriSpeech-dev-other-sint: 100%|██████████| 11456/11456 [00:01<00:00, 7326.53it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-dev-combined/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-dev-combined/audio
Total files: 22268
Total duration: 42.04h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 5567  │
│ good      ┆ 5567  │
│ okay      ┆ 5567  │
│ perfect   ┆ 5567  │
└───────────┴───────┘

shape: (22_268, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/good/127 ┆ BY HARRY       ┆ en       ┆ good      ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0014. ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/127 ┆ BY HARRY       ┆ en       ┆ okay      ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0014. ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/1272 ┆ BY HARRY       ┆ en       ┆ bad       ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ -128104-0014.w ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ av             ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ BY HARRY       ┆ en       ┆ perfect   ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 1272-128104-00 ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ 14…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/127 ┆ AS FOR         ┆ en       ┆ good      ┆ 5.12     ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0008. ┆ ETCHINGS THEY  ┆          ┆           ┆          ┆             ┆ 08             │
│ wa…            ┆ ARE OF TW…     ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/perfect/ ┆ I NEVER        ┆ en       ┆ perfect   ┆ 15.73    ┆ 16000       ┆ 8288-274162-00 │
│ 8288-274162-00 ┆ COMPLAIN AS    ┆          ┆           ┆          ┆             ┆ 35             │
│ 35…            ┆ YOU KNOW B…    ┆          ┆           ┆          ┆             ┆                │
│ audio/good/828 ┆ AND AGAIN WHEN ┆ en       ┆ good      ┆ 26.105   ┆ 16000       ┆ 8288-274150-00 │
│ 8-274150-0000. ┆ THE ARTIST     ┆          ┆           ┆          ┆             ┆ 00             │
│ wa…            ┆ FOLL…          ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/828 ┆ AND AGAIN WHEN ┆ en       ┆ okay      ┆ 26.105   ┆ 16000       ┆ 8288-274150-00 │
│ 8-274150-0000. ┆ THE ARTIST     ┆          ┆           ┆          ┆             ┆ 00             │
│ wa…            ┆ FOLL…          ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/8288 ┆ AND AGAIN WHEN ┆ en       ┆ bad       ┆ 26.105   ┆ 16000       ┆ 8288-274150-00 │
│ -274150-0000.w ┆ THE ARTIST     ┆          ┆           ┆          ┆             ┆ 00             │
│ av             ┆ FOLL…          ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ AND AGAIN WHEN ┆ en       ┆ perfect   ┆ 26.105   ┆ 16000       ┆ 8288-274150-00 │
│ 8288-274150-00 ┆ THE ARTIST     ┆          ┆           ┆          ┆             ┆ 00             │
│ 00…            ┆ FOLL…          ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [10]:
merge_datasets(
    dataset_dirs=[
        DATA_DIR / "LibriSpeech-test-clean-sint",
        DATA_DIR / "LibriSpeech-test-other-sint",
    ],
    output_dir=DATA_DIR / "LibriSpeech-test-combined",
)

Copying LibriSpeech-test-clean-sint: 100%|██████████| 10480/10480 [00:05<00:00, 1940.47it/s]
Copying LibriSpeech-test-other-sint: 100%|██████████| 11756/11756 [00:02<00:00, 3974.38it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-test-combined/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-test-combined/audio
Total files: 22236
Total duration: 42.98h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 5559  │
│ good      ┆ 5559  │
│ okay      ┆ 5559  │
│ perfect   ┆ 5559  │
└───────────┴───────┘

shape: (22_236, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/good/108 ┆ HE TRIED TO    ┆ en       ┆ good      ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0014. ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/108 ┆ HE TRIED TO    ┆ en       ┆ okay      ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0014. ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/1089 ┆ HE TRIED TO    ┆ en       ┆ bad       ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ -134686-0014.w ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ av             ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ HE TRIED TO    ┆ en       ┆ perfect   ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 1089-134686-00 ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ 14…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/good/108 ┆ HELLO BERTIE   ┆ en       ┆ good      ┆ 2.68     ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0003. ┆ ANY GOOD IN    ┆          ┆           ┆          ┆             ┆ 03             │
│ wa…            ┆ YOUR …         ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/perfect/ ┆ THE TEMPLAR IS ┆ en       ┆ perfect   ┆ 16.69    ┆ 16000       ┆ 8461-281231-00 │
│ 8461-281231-00 ┆ FLED SAID DE   ┆          ┆           ┆          ┆             ┆ 30             │
│ 30…            ┆ BR…            ┆          ┆           ┆          ┆             ┆                │
│ audio/good/846 ┆ HE LEFT THE    ┆ en       ┆ good      ┆ 20.21    ┆ 16000       ┆ 8461-281231-00 │
│ 1-281231-0024. ┆ GALLANT BAND   ┆          ┆           ┆          ┆             ┆ 24             │
│ wa…            ┆ OF FO…         ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/846 ┆ HE LEFT THE    ┆ en       ┆ okay      ┆ 20.21    ┆ 16000       ┆ 8461-281231-00 │
│ 1-281231-0024. ┆ GALLANT BAND   ┆          ┆           ┆          ┆             ┆ 24             │
│ wa…            ┆ OF FO…         ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/8461 ┆ HE LEFT THE    ┆ en       ┆ bad       ┆ 20.21    ┆ 16000       ┆ 8461-281231-00 │
│ -281231-0024.w ┆ GALLANT BAND   ┆          ┆           ┆          ┆             ┆ 24             │
│ av             ┆ OF FO…         ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ HE LEFT THE    ┆ en       ┆ perfect   ┆ 20.21    ┆ 16000       ┆ 8461-281231-00 │
│ 8461-281231-00 ┆ GALLANT BAND   ┆          ┆           ┆          ┆             ┆ 24             │
│ 24…            ┆ OF FO…         ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [24]:
import json

atc_train_path = Path(
    "/Users/ezka/PycharmProjects/VHF-ASR/data/ESC50_vhf_simulated-20m"
)

atc_train_manifest_data = []
with open(atc_train_path / "manifest.jsonl", "r") as f:
    for line in f:
        atc_train_manifest_data.append(json.loads(line))

In [25]:
with open(
    "/Users/ezka/PycharmProjects/VHF-ASR/data/LibriSpeech-train-sim-100h/manifest.jsonl",
    "a",
) as f:
    for entry in atc_train_manifest_data:
        f.write(json.dumps(entry) + "\n")

In [26]:
import polars as pl
from paths import ROOT_DIR

train_df = pl.read_ndjson(ROOT_DIR / "data/LibriSpeech-train-sim-100h/manifest.jsonl")

In [27]:
train_df["duration"].sum() / 60 / 60

106.09631999999996

In [4]:
from pathlib import Path
from tqdm import tqdm
import polars as pl
import shutil
from paths import DATA_DIR


def merge_datasets(
    dataset_dirs: list[str | Path],
    output_dir: str | Path,
    manifests: list[str] | str = "manifest.jsonl",
) -> pl.DataFrame:
    output_dir = Path(output_dir)
    audio_dir = output_dir / "audio"
    manifest_path = output_dir / "manifest.jsonl"

    if isinstance(manifests, str):
        manifests = [manifests] * len(dataset_dirs)

    if len(manifests) != len(dataset_dirs):
        raise ValueError(
            f"manifests has {len(manifests)} entries but dataset_dirs has "
            f"{len(dataset_dirs)} — lengths must match."
        )

    all_rows = []

    for dataset_dir, manifest_name in zip(dataset_dirs, manifests):
        dataset_dir = Path(dataset_dir)
        manifest = dataset_dir / manifest_name

        if not manifest.exists():
            raise FileNotFoundError(f"Manifest not found: {manifest}")

        df = pl.read_ndjson(manifest)

        for row in tqdm(
            df.iter_rows(named=True),
            total=len(df),
            desc=f"Copying {dataset_dir.name} ({manifest_name})",
        ):
            src = dataset_dir / row["audio_filepath"]

            condition_dir = audio_dir / row["condition"]
            condition_dir.mkdir(parents=True, exist_ok=True)

            dst = condition_dir / f"{row['utterance_id']}{src.suffix}"

            if dst.exists():
                dst = (
                    condition_dir
                    / f"{dataset_dir.name}__{row['utterance_id']}{src.suffix}"
                )

            shutil.copy2(src, dst)

            row["audio_filepath"] = str(dst.relative_to(output_dir))
            all_rows.append(row)

    new_df = pl.DataFrame(all_rows).select(
        [
            "audio_filepath",
            "text",
            "language",
            "condition",
            "duration",
            "sample_rate",
            "utterance_id",
        ]
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    new_df.write_ndjson(manifest_path)

    print(f"Manifest written to: {manifest_path}")
    print(f"Audio files copied to: {audio_dir}")
    print(f"Total files: {len(new_df)}")
    print(f"Total duration: {new_df['duration'].sum() / 3600:.2f}h")
    print(f"Conditions: {new_df['condition'].value_counts().sort('condition')}")

    return new_df

In [5]:
merge_datasets(
    dataset_dirs=[DATA_DIR / "LibriSpeech-train-final", DATA_DIR / "atc_asr_train"],
    manifests=["manifest.jsonl", "manifest_ecapa.jsonl"],
    output_dir=DATA_DIR / "LibriSpeech-train-final-with-atc",
)

Copying LibriSpeech-train-final (manifest.jsonl): 100%|██████████| 28489/28489 [00:05<00:00, 5263.66it/s]
Copying atc_asr_train (manifest_ecapa.jsonl): 100%|██████████| 6497/6497 [00:00<00:00, 9372.88it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-train-final-with-atc/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-train-final-with-atc/audio
Total files: 34986
Total duration: 106.10h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 7218  │
│ good      ┆ 7269  │
│ okay      ┆ 7220  │
│ perfect   ┆ 13279 │
└───────────┴───────┘

shape: (34_986, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/perfect/ ┆ THE INFANT     ┆ en       ┆ perfect   ┆ 15.895   ┆ 16000       ┆ 8425-291444-00 │
│ 8425-291444-00 ┆ YEARS OF OUR   ┆          ┆           ┆          ┆             ┆ 13             │
│ 13…            ┆ CITY T…        ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ CHAPTER TWENTY ┆ en       ┆ perfect   ┆ 15.105   ┆ 16000       ┆ 3807-4955-0000 │
│ 3807-4955-0000 ┆ FIVE THE       ┆          ┆           ┆          ┆             ┆                │
│ .w…            ┆ FLIGHT…        ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/481 ┆ THERE WERE     ┆ en       ┆ okay      ┆ 15.61    ┆ 16000       ┆ 481-123719-000 │
│ -123719-0006.w ┆ MOMENTS OF     ┆          ┆           ┆          ┆             ┆ 6              │
│ av             ┆ SUCH POS…      ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/89- ┆ TO CLOSE HER   ┆ en       ┆ okay      ┆ 15.29    ┆ 16000       ┆ 89-218-0054    │
│ 218-0054.wav   ┆ EYES IN SLEEP  ┆          ┆           ┆          ┆             ┆                │
│                ┆ THA…           ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ BUT STOOD      ┆ en       ┆ perfect   ┆ 15.695   ┆ 16000       ┆ 3526-176653-00 │
│ 3526-176653-00 ┆ STILL WINDING  ┆          ┆           ┆          ┆             ┆ 08             │
│ 08…            ┆ SOMETH…        ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.94     ┆ 16000       ┆ ZZO15U50FH61N7 │
│ ZZO15U50FH61N7 ┆                ┆          ┆           ┆          ┆             ┆ FDRFQX         │
│ FD…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.35     ┆ 16000       ┆ ZZRJO7VBHH5OL5 │
│ ZZRJO7VBHH5OL5 ┆                ┆          ┆           ┆          ┆             ┆ U7NTED         │
│ U7…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 3.06     ┆ 16000       ┆ ZZSFZ2ZR9GHXZQ │
│ ZZSFZ2ZR9GHXZQ ┆                ┆          ┆           ┆          ┆             ┆ UHN8L6         │
│ UH…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 0.78     ┆ 16000       ┆ ZZXH711NQKSIIN │
│ ZZXH711NQKSIIN ┆                ┆          ┆           ┆          ┆             ┆ TYSAAC         │
│ TY…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 4.66     ┆ 16000       ┆ ZZYAGZR64L4YWP │
│ ZZYAGZR64L4YWP ┆                ┆          ┆           ┆          ┆             ┆ 6CBC5T         │
│ 6C…            ┆                ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [6]:
merge_datasets(
    dataset_dirs=[DATA_DIR / "LibriSpeech-dev-combined", DATA_DIR / "atc_asr_val"],
    manifests=["manifest.jsonl", "manifest_ecapa.jsonl"],
    output_dir=DATA_DIR / "LibriSpeech-dev-combined-with-atc",
)

Copying LibriSpeech-dev-combined (manifest.jsonl): 100%|██████████| 22268/22268 [00:03<00:00, 7276.51it/s]
Copying atc_asr_val (manifest_ecapa.jsonl): 100%|██████████| 812/812 [00:00<00:00, 9517.59it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-dev-combined-with-atc/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-dev-combined-with-atc/audio
Total files: 23080
Total duration: 42.78h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 5574  │
│ good      ┆ 5584  │
│ okay      ┆ 5586  │
│ perfect   ┆ 6336  │
└───────────┴───────┘

shape: (23_080, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/good/127 ┆ BY HARRY       ┆ en       ┆ good      ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0014. ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/127 ┆ BY HARRY       ┆ en       ┆ okay      ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0014. ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/1272 ┆ BY HARRY       ┆ en       ┆ bad       ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ -128104-0014.w ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ av             ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ BY HARRY       ┆ en       ┆ perfect   ┆ 2.245    ┆ 16000       ┆ 1272-128104-00 │
│ 1272-128104-00 ┆ QUILTER M A    ┆          ┆           ┆          ┆             ┆ 14             │
│ 14…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/good/127 ┆ AS FOR         ┆ en       ┆ good      ┆ 5.12     ┆ 16000       ┆ 1272-128104-00 │
│ 2-128104-0008. ┆ ETCHINGS THEY  ┆          ┆           ┆          ┆             ┆ 08             │
│ wa…            ┆ ARE OF TW…     ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 0.75     ┆ 16000       ┆ ZKWSSNML4C7F4Y │
│ ZKWSSNML4C7F4Y ┆                ┆          ┆           ┆          ┆             ┆ GF76ST         │
│ GF…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.49     ┆ 16000       ┆ ZNKQ5A36E1JQQX │
│ ZNKQ5A36E1JQQX ┆                ┆          ┆           ┆          ┆             ┆ F2A8JC         │
│ F2…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.71     ┆ 16000       ┆ ZQ1VKVV411QIZR │
│ ZQ1VKVV411QIZR ┆                ┆          ┆           ┆          ┆             ┆ MT0NHB         │
│ MT…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 3.2      ┆ 16000       ┆ ZQW6L87PSCH8Q7 │
│ ZQW6L87PSCH8Q7 ┆                ┆          ┆           ┆          ┆             ┆ QRERIK         │
│ QR…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.94     ┆ 16000       ┆ ZTS55C2IBJVSLR │
│ ZTS55C2IBJVSLR ┆                ┆          ┆           ┆          ┆             ┆ DMZVXY         │
│ DM…            ┆                ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘

In [7]:
merge_datasets(
    dataset_dirs=[DATA_DIR / "LibriSpeech-test-combined", DATA_DIR / "atc_asr_test"],
    manifests=["manifest.jsonl", "manifest_ecapa.jsonl"],
    output_dir=DATA_DIR / "LibriSpeech-test-combined-with-atc",
)

Copying LibriSpeech-test-combined (manifest.jsonl): 100%|██████████| 22236/22236 [00:03<00:00, 6783.21it/s]
Copying atc_asr_test (manifest_ecapa.jsonl): 100%|██████████| 813/813 [00:00<00:00, 8917.14it/s]

Manifest written to: /home/ezka/vhf-bak/data/LibriSpeech-test-combined-with-atc/manifest.jsonl
Audio files copied to: /home/ezka/vhf-bak/data/LibriSpeech-test-combined-with-atc/audio
Total files: 23049
Total duration: 43.74h
Conditions: shape: (4, 2)
┌───────────┬───────┐
│ condition ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ bad       ┆ 5560  │
│ good      ┆ 5576  │
│ okay      ┆ 5574  │
│ perfect   ┆ 6339  │
└───────────┴───────┘

shape: (23_049, 7)
┌────────────────┬────────────────┬──────────┬───────────┬──────────┬─────────────┬────────────────┐
│ audio_filepath ┆ text           ┆ language ┆ condition ┆ duration ┆ sample_rate ┆ utterance_id   │
│ ---            ┆ ---            ┆ ---      ┆ ---       ┆ ---      ┆ ---         ┆ ---            │
│ str            ┆ str            ┆ str      ┆ str       ┆ f64      ┆ i64         ┆ str            │
╞════════════════╪════════════════╪══════════╪═══════════╪══════════╪═════════════╪════════════════╡
│ audio/good/108 ┆ HE TRIED TO    ┆ en       ┆ good      ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0014. ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/okay/108 ┆ HE TRIED TO    ┆ en       ┆ okay      ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0014. ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ wa…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/bad/1089 ┆ HE TRIED TO    ┆ en       ┆ bad       ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ -134686-0014.w ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ av             ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ HE TRIED TO    ┆ en       ┆ perfect   ┆ 2.225    ┆ 16000       ┆ 1089-134686-00 │
│ 1089-134686-00 ┆ THINK HOW IT   ┆          ┆           ┆          ┆             ┆ 14             │
│ 14…            ┆ COULD…         ┆          ┆           ┆          ┆             ┆                │
│ audio/good/108 ┆ HELLO BERTIE   ┆ en       ┆ good      ┆ 2.68     ┆ 16000       ┆ 1089-134686-00 │
│ 9-134686-0003. ┆ ANY GOOD IN    ┆          ┆           ┆          ┆             ┆ 03             │
│ wa…            ┆ YOUR …         ┆          ┆           ┆          ┆             ┆                │
│ …              ┆ …              ┆ …        ┆ …         ┆ …        ┆ …           ┆ …              │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 3.56     ┆ 16000       ┆ ZRVW14Z2FO4EZP │
│ ZRVW14Z2FO4EZP ┆                ┆          ┆           ┆          ┆             ┆ 98Y33S         │
│ 98…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 3.0      ┆ 16000       ┆ ZUKPIHDOAU3FN9 │
│ ZUKPIHDOAU3FN9 ┆                ┆          ┆           ┆          ┆             ┆ X1BS2Z         │
│ X1…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.36     ┆ 16000       ┆ ZXGUAKVXT2FHO8 │
│ ZXGUAKVXT2FHO8 ┆                ┆          ┆           ┆          ┆             ┆ CC98E3         │
│ CC…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.73     ┆ 16000       ┆ ZYNR929BWV5ABN │
│ ZYNR929BWV5ABN ┆                ┆          ┆           ┆          ┆             ┆ L5ND5R         │
│ L5…            ┆                ┆          ┆           ┆          ┆             ┆                │
│ audio/perfect/ ┆ null           ┆ en       ┆ perfect   ┆ 2.57     ┆ 16000       ┆ ZZ0Q4Q496US5DS │
│ ZZ0Q4Q496US5DS ┆                ┆          ┆           ┆          ┆             ┆ P6W2W6         │
│ P6…            ┆                ┆          ┆           ┆          ┆             ┆                │
└────────────────┴────────────────┴──────────┴───────────┴──────────┴─────────────┴────────────────┘